name: 🚀 Deploy to TEST Hosting and Functions

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to TEST Hosting and Functions
        run: firebase deploy --only hosting,functions
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
